export const ADD_NOTICE_REQUEST = "ADD_NOTICE_REQUEST";
export const ADD_NOTICE_SUCCESS = "ADD_NOTICE_SUCCESS";
export const ADD_NOTICE_FAILED = "ADD_NOTICE_FAILED";

export const GET_ALL_NOTICE_REQUEST = "GET_ALL_NOTICE_REQUEST";
export const GET_ALL_NOTICE_SUCCESS = "GET_ALL_NOTICE_SUCCESS";
export const GET_ALL_NOTICE_FAILED = "GET_ALL_NOTICE_FAILED";

export const GET_NOTICE_DETAILS_REQUEST = "GET_NOTICE_DETAILS_REQUEST";
export const GET_NOTICE_DETAILS_SUCCESS = "GET_NOTICE_DETAILS_SUCCESS";
export const GET_NOTICE_DETAILS_FAILED = "GET_NOTICE_DETAILS_FAILED";

export const UPDATE_NOTICE_REQUEST = "UPDATE_NOTICE_REQUEST";
export const UPDATE_NOTICE_SUCCESS = "UPDATE_NOTICE_SUCCESS";
export const UPDATE_NOTICE_FAILED = "UPDATE_NOTICE_FAILED";
export const UPDATE_NOTICE_RESET = "UPDATE_NOTICE_RESET";

export const DELETE_NOTICE_REQUEST = "DELETE_NOTICE_REQUEST";
export const DELETE_NOTICE_SUCCESS = "DELETE_NOTICE_SUCCESS";
export const DELETE_NOTICE_FAILED = "DELETE_NOTICE_FAILED";
export const DELETE_NOTICE_RESET = "DELETE_NOTICE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
