export const ADD_NEW_STAFF_FAILED = "ADD_NEW_STAFF_FAILED";
export const ADD_NEW_STAFF_REQUEST = "ADD_NEW_STAFF_REQUEST";
export const ADD_NEW_STAFF_SUCCESS = "ADD_NEW_STAFF_SUCCESS";

export const GET_ALL_STAFFS_REQUEST= "GET_ALL_STAFF_REQUEST";
export const GET_ALL_STAFFS_SUCCESS= "GET_ALL_STAFF_SUCCESS";
export const GET_ALL_STAFFS_FAILED= "GET_ALL_STAFF_FAILED";

export const STAFF_DETAILS_REQUST = "STAFF_DETAILS_REQUST";
export const STAFF_DETAILS_SUCCESS = "STAFF_DETAILS_SUCCESS";
export const STAFF_DETAILS_FAILED = "STAFF_DETAILS_FAILED";

export const STAFF_UPDATE_REQUST = "STAFF_UPDATE_REQUST";
export const STAFF_UPDATE_SUCCESS = "STAFF_UPDATE_SUCCESS";
export const STAFF_UPDATE_FAILED = "STAFF_UPDATE_FAILED";
export const STAFF_UPDATE_RESET = "STAFF_UPDATE_RESET";

export const STAFF_DELETE_REQUST = "STAFF_DELETE_REQUST";
export const STAFF_DELETE_SUCCESS = "STAFF_DELETE_SUCCESS";
export const STAFF_DELETE_FAILED = "STAFF_DELETE_FAILED";
export const STAFF_DELETE_RESET = "STAFF_DELETE_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
