export const ALL_NOTICE_REQUEST = "ALL_NOTICE_REQUEST";
export const ALL_NOTICE_SUCCESS = "ALL_NOTICE_SUCCESS";
export const ALL_NOTICE_FAILED = "ALL_NOTICE_FAILED";

export const GET_TEACHERS_REQUEST = "GET_TEACHERS_REQUEST";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_FAILD = "GET_TEACHERS_FALLD";

export const ADD_NEW_TEACHER_REQUEST = "ADD_NEW_TEACHER_REQUEST";
export const ADD_NEW_TEACHER_SUCCESS = "ADD_NEW_TEACHER_SUCCESS";
export const ADD_NEW_TEACHER_FAILED = "ADD_NEW_TEACHER_FAILED";

export const GET_ALL_TEACHER_REQUEST = "GET_ALL_TEACHER_REQUEST";
export const GET_ALL_TEACHER_SUCCESS = "GET_ALL_TEACHER_SUCCESS";
export const GET_ALL_TEACHER_FAILED = "GET_ALL_TEACHER_FAILED";

export const GET_TEACHERS_DETAILS_REQUEST = "GET_TEACHERS_DETAILS_REQUEST";
export const GET_TEACHERS_DETAILS_SUCCESS = "GET_TEACHERS_DETAILS_SUCCESS";
export const GET_TEACHERS_DETAILS_FAILED = "GET_TEACHERS_DETAILS_FAILED";

export const UPDATE_TEACHERS_REQUEST = "UPDATE_TEACHERS_REQUEST";
export const UPDATE_TEACHERS_SUCCESS = "UPDATE_TEACHERS_SUCCESS";
export const UPDATE_TEACHERS_FAILED = "UPDATE_TEACHERS_FAILED";
export const UPDATE_TEACHERS_RESET = "UPDATE_TEACHERS_RESET";

export const DELETE_TEACHER_REQUEST="DELETE_TEACHER_REQUEST"
export const DELETE_TEACHER_SUCCESS="DELETE_TEACHER_SUCCESS"
export const DELETE_TEACHER_FAILED="DELETE_TEACHER_FAILED"
export const DELETE_TEACHER_RESET="DELETE_TEACHER_RESET"

export const CLEAR_ERRORS = "CEAR_ERRORS";
